config/routes.rb
Rails.application.routes.draw do
 
  get 'admin/users'
    get 'admin/users/:id/change' => 'admin#change'

  devise_for :users
  root 'works#index'

  resources :works
 
  resources :makers

end

app/models/maker.rb
class Maker < ActiveRecord::Base
    has_many :works
    
    # name 반드시 있어야하고, 두 글자 이상
    # email 반드시 있어야하고, 세 글자 이상
    # phone_number 반드시 있어야하고, 8글자 이상
    
    validates :name,
        presence: true,
        length: {minimum: 2}
    
    validates :email,
        presence: true,
        length: {minimum: 3},
        format: {with: /\A[^@\s]+@[^@\s]+\z/ }
    
    validates :phone_number,
        presence: true,
        length: {minimum: 8}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ActiveRecord::Base
    mount_uploader(:image, ImageUploader)
    validates_presence_of :image # carrierwave 를 통해 검증
    
    belongs_to :maker
    
    validates :title, 
        presence: true
    
    validates :desc, 
        presence: true, 
        length: {minimum: 3}
    validates :image,
        presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :check_admin
    
    def users
        @users = User.all
    end
    
    def change
        # 해당하는 유저의 역할을 바꾼다.
       # 1. 만약에 관리자면 -> 양민
       # 2. 아니면 -> 관리자
       user = User.find(params[:id])
       if user.is_admin?
           user.update(
            is_admin?: false    
           )
       else
           user.update(
            is_admin?: true    
           )
       end
       redirect_to '/admin/users'
    end
    
    def check_admin
        unless current_user.is_admin?
            flash[:alert] ="양민은 들어올 수 없습니다."
            redirect_to '/'
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/makers_controller.rb
class MakersController < ApplicationController
  def index
    @makers = Maker.all
  end

  def new
    
  end

  def create
    maker = Maker.new(
      name: params[:name],
      phone_number: params[:phone_number],
      email: params[:email]
      )
    maker.save
    redirect_to root_path
  end

  def show
    @maker = Maker.find(params[:id])
  end

  def edit
    @maker = Maker.find(params[:id])
  end

  def update
    @maker = Maker.find(params[:id])
    @maker.update(
      name: params[:name],
      phone_number: params[:phone_number],
      email: params[:email],
    )
    redirect_to "/makers/#{@maker.id}"
  end

  def destroy
    @maker = Maker.find(params[:id])
    @maker.destroy
    redirect_to makers_path
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def index
    #모든작품을보여준다.
    @works = Work.all
  end

  def new
    @makers = Maker.all
  end

  def create
    # Work 데이터베이스에 만들겠다.
    work = Work.new(
      title: params[:title],
      desc: params[:desc],
      image: params[:image],
      maker_id: params[:maker_id]
    )
    if work.save
    redirect_to "/works/#{work.id}"
    else
     flash[:msg] = "제목 혹은 내용이 비어있으면 안됩니다."
     redirect_to new_work_path
    end
  end

  def show
    @work = Work.find(params[:id])
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])
    @work.update(
      title: params[:title],
      desc: params[:desc],
      image: params[:image],
      maker_id: params[:maker_id]
    )
    redirect_to "/works/#{@work.id}"
  end

  def destroy
    # 지우고자 하는 글을 지운다.
    @work = Work.find(params[:id])
    @work.destroy
    redirect_to works_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/admin/users.erb
<h1>회원정보</h1>
<!--회원정보(이메일, 관리자 여부)-->
<table>
    <tr>
        <th>이메일</th>
        <th>역할</th>
        <th>로그인 횟수</th>
        <th>로그인 시간</th>
        <th>로그인 ip</th>

    </tr>
    <% @users.each do |user|%>
    <tr>
        <td><%= user.email %></td>
        <td><%= user.is_admin? ? "관리자" : "양민" %></td>
        <td><%= user.sign_in_count %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        
        
        <td><%= link_to "역할바꾸기", "/admin/users/#{user.id}/change", data: {confirm: "진짜?"} %></td>
        
    </tr>
    
    <% end %>
</table>

app/views/layouts/_header.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">3D Print반 전시회</h4>
          <p class="text-muted">전시회 정보</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">유저정보</h4>
          <ul class="list-unstyled">
            <% if user_signed_in? %>
            <li style="color: white;"><%= link_to '로그아웃', destroy_user_session_path, method: :delete %></li>
            <li style="color: white;"><%= current_user.email %>님 환영합니다.</li>
            <% else %>
            <li style="color: white;"><%= link_to '로그인', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>3D Print반 전시회</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <link rel="stylesheet" href="https://getbootstrap.com/docs/4.1/examples/album/album.css"
</head>
<body>
  <%= render 'layouts/header'%>

  <div class="alert alert-primary" role="alert">
    <%= notice %>
    <%= alert %>
  </div>
   
<%= yield %>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

</body>
</html>

app/views/makers/create.html.erb
<h1>Makers#create</h1>
<p>Find me in app/views/makers/create.html.erb</p>

app/views/makers/destroy.html.erb
<h1>Makers#destroy</h1>
<p>Find me in app/views/makers/destroy.html.erb</p>

app/views/makers/edit.html.erb
<h1>수정하기</h1>

<%= form_tag("/makers/#{@maker.id}", method: "put") do %>
    이름 : <%= text_field_tag(:name, @maker.name) %><br>
    연락처 : <%= text_field_tag(:phone_number, @maker.phone_number) %><br>
    이메일 : <%= text_field_tag(:email, @maker.email) %><br>
    <%= submit_tag("제출") %>
<% end %>

app/views/makers/index.html.erb
<h1>작가 정보</h1>
<%= link_to '새 작가 올리기', new_maker_path %>
<table>
    <tr>
        <th>이름</th>
        <th>이메일</th>
    </tr>
    
    <% @makers.each do |m| %>
    <tr>
        <td><%= m.name %></td>
        <td><%= m.email %></td>
        <td><%= link_to "연락처 보기","/makers/#{m.id}" %></td>
        <td><%= link_to "수정","/makers/#{m.id}/edit" %></td>
        <td><%= link_to "삭제","/makers/#{m.id}", method:"delete", data: {confirm: "삭제하시겠습니까?"}  %></td>
    </tr>
    <% end %>
</table>

app/views/makers/new.html.erb
<h1>새 작가 업로드</h1>

<%= form_tag("/makers") do %>
    이름 : <%= text_field_tag(:name) %><br>
    연락처 : <%= text_field_tag(:phone_number) %><br>
    이메일 : <%= email_field_tag(:email) %><br>
    <%= submit_tag("작가추가") %>
<% end %>

app/views/makers/show.html.erb
<h1><%= @maker.name %>의 연락처</h1>
핸드폰 : <%= @maker.phone_number %>
이메일 : <%= @maker.email %>

app/views/makers/update.html.erb
<h1>Makers#update</h1>
<p>Find me in app/views/makers/update.html.erb</p>

app/views/works/create.html.erb
<h1>작품 올리기</h1>
<p>내용 넣기</p>
<%= link_to "다시 만들러 가기", "/works/new" %>

app/views/works/destroy.html.erb
<h1>Works#destroy</h1>
<p>Find me in app/views/works/destroy.html.erb</p>

app/views/works/edit.html.erb
<h1>수정하기</h1>

<%= form_tag("/works/#{@work.id}", method: "put") do %>
    제목 : <%= text_field_tag(:title, @work.title) %><br>
    설명 : <%= text_field_tag(:desc, @work.desc) %><br>
    이미지url : <%= text_field_tag(:image, @work.image) %><br>
    메이커_id : <%= text_field_tag(:maker_id, @work.maker_id) %><br>
    <%= submit_tag("작품 올리기") %>
<% end %>

app/views/works/index.html.erb
<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">3D Print 전시회</h1>
      <p class="lead text-muted">멀티캠퍼스 4차산업혁명선도인력양성 3D Print반 최종 프로젝트</p>
      <p>
        <% if user_signed_in? and current_user.is_admin? %>
            <%= link_to '새 작품 올리기', new_work_path, class: "btn btn-primary my-2"%>
            <%= link_to '새 작가 올리기', new_maker_path, class: "btn btn-primary my-2" %>
            <%= link_to '관리자 페이지', '/admin/users', class: "btn btn-primary my-2" %>
        <% end %>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        <% @works.each do|w| %>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <img class="card-img-top" src = "<%= w.image%>" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"><%= w.title %></h5>
              <p class="card-text"><%= w.desc %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to '상세보기', "/works/#{w.id}"%></button>
                  <% if user_signed_in? %>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to '수정', "/works/#{w.id}/edit"%></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to '삭제하기', "/works/#{w.id}", method: "delete", data: {confirm: "진짜?"} %></button>
                  <% end %>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

</main>

app/views/works/new.html.erb
<p><%= flash[:msg] %></p>

<h1>새 작품 업로드</h1>

<%= form_tag("/works", multipart: true) do %>
    제목 : <%= text_field_tag(:title) %><br>
    설명 : <%= text_field_tag(:desc) %><br>
    이미지url : <%= file_field_tag(:image) %><br>
    메이커_id : 
    <select name="maker_id">
        <% @makers.each do |maker| %>
            <option value="<%= maker.id %>"><%= maker.name %></option>
        <% end %>
    </select><br>
    <%= submit_tag("작품 올리기") %>
<% end %>

app/views/works/show.html.erb
<h1><%= @work.title %></h1>
<img src="<%= @work.image %>">
<p><%= @work.desc %></p>
<p>메이커 : <%= @work.maker.name %></p>

app/views/works/update.html.erb
<h1>Works#update</h1>
<p>Find me in app/views/works/update.html.erb</p>